spring:
  application:
    name: 'producer'
producer:
  loader:
    pingFileSchedule: 0 0 1 * * ? # Every day at 1 am
    ping: 0/30 * * * * *   #every 30 seconds.
kafka:
  topic_product: 'bank-products'
  topic_customer: 'bank-customers'
  bootstrapAddress: 'localhost:9092'
  group.id: 'customer'
